name: 'Changelog action'
description: 'Parse markdown files, generate releases, tweet notes and send to Discord'
author: 'Hyperbeam Inc'
inputs:
  file:
    required: true
    description: 'The changelog markdown file to parse'
runs:
  using: 'node16'
  main: 'dist/index.js'
